alter table PLATFORMSAMPLEPORTAL_ORDERS_FOOD_LINK add constraint FK_POFL_ORDERS foreign key (ORDERS_ID) references PLATFORMSAMPLEPORTAL_ORDERS(ID);
alter table PLATFORMSAMPLEPORTAL_ORDERS_FOOD_LINK add constraint FK_POFL_FOOD foreign key (FOOD_ID) references PLATFORMSAMPLEPORTAL_FOOD(ID);
