alter table PLATFORMSAMPLEPORTAL_ORDERS add constraint FK_PLATFORMSAMPLEPORTAL_ORDERS_USER_ID foreign key (USER_ID) references SEC_USER(ID);
create index IDX_PLATFORMSAMPLEPORTAL_ORDERS_USER on PLATFORMSAMPLEPORTAL_ORDERS (USER_ID);
