alter table PLATFORMSAMPLEPORTAL_ORDER_FOOD_LINK add constraint FK_POFL_ORDER foreign key (ORDER_ID) references PLATFORMSAMPLEPORTAL_ORDER(ID);
alter table PLATFORMSAMPLEPORTAL_ORDER_FOOD_LINK add constraint FK_POFL_FOOD foreign key (FOOD_ID) references PLATFORMSAMPLEPORTAL_FOOD(ID);
