alter table PLATFORMSAMPLEPORTAL_ORDER add constraint FK_PLATFORMSAMPLEPORTAL_ORDER_USER_ID foreign key (USER_ID) references SEC_USER(ID);
alter table PLATFORMSAMPLEPORTAL_ORDER add constraint FK_PLATFORMSAMPLEPORTAL_ORDER_STATUS_ID foreign key (STATUS_ID) references PLATFORMSAMPLEPORTAL_STATUS(ID);
create index IDX_PLATFORMSAMPLEPORTAL_ORDER_USER on PLATFORMSAMPLEPORTAL_ORDER (USER_ID);
create index IDX_PLATFORMSAMPLEPORTAL_ORDER_STATUS on PLATFORMSAMPLEPORTAL_ORDER (STATUS_ID);
