-- begin PLATFORMSAMPLEPORTAL_ORDER
alter table PLATFORMSAMPLEPORTAL_ORDER add constraint FK_PLATFORMSAMPLEPORTAL_ORDER_USER_ID foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PLATFORMSAMPLEPORTAL_ORDER_USER on PLATFORMSAMPLEPORTAL_ORDER (USER_ID)^
-- end PLATFORMSAMPLEPORTAL_ORDER
-- begin PLATFORMSAMPLEPORTAL_ORDER_FOOD_LINK
alter table PLATFORMSAMPLEPORTAL_ORDER_FOOD_LINK add constraint FK_POFL_ORDER foreign key (ORDER_ID) references PLATFORMSAMPLEPORTAL_ORDER(ID)^
alter table PLATFORMSAMPLEPORTAL_ORDER_FOOD_LINK add constraint FK_POFL_FOOD foreign key (FOOD_ID) references PLATFORMSAMPLEPORTAL_FOOD(ID)^
-- end PLATFORMSAMPLEPORTAL_ORDER_FOOD_LINK
